name: Sauvegarde Base de données
on: push
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/
  
  SauvegardeBDD:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/
            sqlite3 database.db .dump > sauvegarde.sql
  CopyBDD:
    needs: SauvegardeBDD
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAMED }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
           apt-get install sshpass
           ssh-keyscan -H ${{ secrets.USERNAME }}.alwaysdata.net >> ~/.ssh/known_hosts
           cd $HOME/www/
           sshpass -p ${{ secrets.PASSWORDDIST }} scp sauvegarde.sql stockerboris_1@ssh-etudiant.alwaysdata.net:./www/
